// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProperTabGroups
{
    internal sealed partial class Vsix
    {
        public const string Id = "ProperTabGroups.c2c6a391-b567-4dfd-99af-327ca6595cd5";
        public const string Name = "ProperTabGroups";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Michael Burdge";
        public const string Tags = "";
    }
}
