// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProperTabGroups
{
    internal sealed partial class Vsix
    {
        public const string Id = "ProperTabGroups.828acccc-9a46-484a-bc1e-d49cb6de4ab5";
        public const string Name = "ProperTabGroups";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Michael Burdge";
        public const string Tags = "";
    }
}
