// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProperTabGroups
{
    internal sealed partial class Vsix
    {
        public const string Id = "ProperTabGroups.b5ed6cef-9e97-4a6f-8247-64ed7919da54";
        public const string Name = "ProperTabGroups";
        public const string Description = @"Proper Tab Groups ORIGINAL";
        public const string Language = "en-US";
        public const string Version = "1.69";
        public const string Author = "Michael Burdge";
        public const string Tags = "";
    }
}
