// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace ProperTabGroups
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string ProperTabGroupsString = "55fd3ffc-fff4-4d9d-94bb-39b88bd35139";
        public static Guid ProperTabGroups = new Guid(ProperTabGroupsString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
    }
}